# Generated by Django 4.0.3 on 2022-03-23 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_slug_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(default='all', on_delete=django.db.models.deletion.PROTECT, related_name='psots', to='blog.category'),
        ),
    ]
